using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace EasyPeasy.SourceGenerator;

/// <summary>Writes the C# source for the generated clients.</summary>
internal static class Emitter
{
    private const string GeneratedCode =
        "[global::System.CodeDom.Compiler.GeneratedCode(\"EasyPeasy.SourceGenerator\", \"3.0.0\")]";

    public static string Emit(string assemblyName, IReadOnlyList<InterfaceModel> interfaces)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CA2255 // ModuleInitializer is how generated clients register themselves");
        builder.AppendLine();
        builder.AppendLine("namespace EasyPeasy.Generated");
        builder.AppendLine("{");

        var proxyNames = new List<(InterfaceModel Interface, string ProxyName)>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var model in interfaces)
        {
            string proxyName = UniqueName(ProxyName(model.FullName), usedNames);
            proxyNames.Add((model, proxyName));
            EmitProxy(builder, model, proxyName);
        }

        builder.AppendLine("    /// <summary>Registers the EasyPeasy clients generated for this assembly.</summary>");
        builder.AppendLine("    " + GeneratedCode);
        builder.AppendLine("    internal static class EasyPeasyClients_" + Sanitize(assemblyName));
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Register()");
        builder.AppendLine("        {");
        foreach (var (model, proxyName) in proxyNames)
        {
            builder.AppendLine($"            global::EasyPeasy.Runtime.ProxyRegistry.Register<{model.FullName}>(static context => new {proxyName}(context));");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitProxy(StringBuilder builder, InterfaceModel model, string proxyName)
    {
        builder.AppendLine($"    /// <summary>The generated EasyPeasy client for <see cref=\"{model.FullName.Replace("global::", string.Empty).Replace('<', '{').Replace('>', '}')}\"/>.</summary>");
        builder.AppendLine("    " + GeneratedCode);
        builder.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCode]");
        builder.AppendLine($"    file sealed class {proxyName} : {model.FullName}");
        builder.AppendLine("    {");

        for (int i = 0; i < model.Methods.Length; i++)
        {
            EmitTemplate(builder, model.Methods[i], i);
        }

        builder.AppendLine();
        builder.AppendLine("        private readonly global::EasyPeasy.Runtime.ClientContext __context;");
        builder.AppendLine();
        builder.AppendLine($"        public {proxyName}(global::EasyPeasy.Runtime.ClientContext context) => __context = context;");

        for (int i = 0; i < model.Methods.Length; i++)
        {
            builder.AppendLine();
            EmitMethod(builder, model.Methods[i], i);
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitTemplate(StringBuilder builder, MethodModel method, int index)
    {
        builder.Append($"        private static readonly global::EasyPeasy.Runtime.RequestTemplate __template{index} = new(");
        builder.Append(method.HttpMethod).Append(", ");
        builder.Append(Literal(method.Path)).Append(", ");
        builder.Append("accept: ").Append(Literal(method.Accept)).Append(", ");
        builder.Append("contentType: ").Append(Literal(method.ContentType)).Append(", ");
        builder.Append("headers: ");
        if (method.Headers.Length == 0)
        {
            builder.Append("null");
        }
        else
        {
            builder.Append("new global::System.Collections.Generic.KeyValuePair<string, string>[] { ");
            builder.Append(string.Join(", ", method.Headers.Select(h => $"new({Literal(h.Name)}, {Literal(h.Value)})")));
            builder.Append(" }");
        }

        builder.Append(", isMultipart: ").Append(method.IsMultipart ? "true" : "false");
        builder.AppendLine(");");
    }

    private static void EmitMethod(StringBuilder builder, MethodModel method, int index)
    {
        string parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Identifier}"));
        builder.AppendLine($"        {method.ReturnType} {method.DeclaringInterface}.{method.Name}({parameters})");
        builder.AppendLine("        {");
        builder.AppendLine($"            var __request = __context.CreateRequest(__template{index});");

        string cancellationToken = "default";
        foreach (var parameter in method.Parameters)
        {
            string key = Literal(parameter.Key);
            switch (parameter.Kind)
            {
                case ParameterKind.Path:
                    builder.AppendLine($"            __request.AddPathParameter({key}, {parameter.Identifier});");
                    break;
                case ParameterKind.Query:
                    builder.AppendLine($"            __request.AddQueryParameter({key}, {parameter.Identifier});");
                    break;
                case ParameterKind.Header:
                    builder.AppendLine($"            __request.AddHeader({key}, {parameter.Identifier});");
                    break;
                case ParameterKind.Form:
                    builder.AppendLine($"            __request.AddFormField({key}, {parameter.Identifier});");
                    break;
                case ParameterKind.Body:
                    builder.AppendLine($"            __request.SetBody<{parameter.Type}>({parameter.Identifier});");
                    break;
                case ParameterKind.CancellationToken:
                    cancellationToken = parameter.Identifier;
                    break;
            }
        }

        string call = method.ReturnKind switch
        {
            ReturnKind.Void => $"__request.SendAsync({cancellationToken})",
            ReturnKind.Result => $"__request.SendAsync<{method.ResultType}>({cancellationToken})",
            ReturnKind.ApiResponse => $"__request.SendForApiResponseAsync({cancellationToken})",
            ReturnKind.ApiResponseOf => $"__request.SendForApiResponseAsync<{method.ResultType}>({cancellationToken})",
            ReturnKind.AsyncEnumerable => $"__request.StreamAsync<{method.ResultType}>({cancellationToken})",
            _ => throw new InvalidOperationException("Unknown return kind " + method.ReturnKind),
        };

        if (method.IsValueTask)
        {
            call = $"new {method.ReturnType}({call})";
        }

        builder.AppendLine($"            return {call};");
        builder.AppendLine("        }");
    }

    private static string Literal(string? value) =>
        value is null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true);

    private static string ProxyName(string fullName) =>
        Sanitize(fullName.Replace("global::", string.Empty)) + "_EasyPeasyClient";

    private static string Sanitize(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (char c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return builder.ToString();
    }

    private static string UniqueName(string name, HashSet<string> used)
    {
        string candidate = name;
        for (int i = 2; !used.Add(candidate); i++)
        {
            candidate = name + i.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        return candidate;
    }
}
